/*
 * Njiwa Open Source Embedded M2M UICC Remote Subscription Manager
 * 
 * 
 * Copyright (C) 2019 - , Digital Solutions Ltd. - http://www.dsmagic.com
 *
 * Njiwa Dev <dev@njiwa.io>
 * 
 * This program is free software, distributed under the terms of
 * the GNU General Public License.
 */ 

/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package io.njiwa.dp.pedefinitions;

import org.openmuc.jasn1.ber.BerByteArrayOutputStream;
import org.openmuc.jasn1.ber.BerIdentifier;
import org.openmuc.jasn1.ber.BerLength;
import org.openmuc.jasn1.ber.types.BerNull;

import java.io.IOException;
import java.io.InputStream;


public class ServicesList {

	public static final BerIdentifier identifier = new BerIdentifier(BerIdentifier.UNIVERSAL_CLASS, BerIdentifier.CONSTRUCTED, 16);
	protected BerIdentifier id;

	public byte[] code = null;
	private BerNull contactless = null;

	private BerNull usim = null;

	private BerNull isim = null;

	private BerNull csim = null;

	private BerNull milenage = null;

	private BerNull tuak128 = null;

	private BerNull cave = null;

	private BerNull gbaUsim = null;

	private BerNull gbaIsim = null;

	private BerNull mbms = null;

	private BerNull eap = null;

	private BerNull javacard = null;

	private BerNull multos = null;

	private BerNull multipleUsim = null;

	private BerNull multipleIsim = null;

	private BerNull multipleCsim = null;

	private BerNull tuak256 = null;

	public ServicesList() {
		id = identifier;
	}

	public ServicesList(byte[] code) {
		id = identifier;
		this.code = code;
	}

	public void setContactless(BerNull contactless) {
		this.contactless = contactless;
	}

	public BerNull getContactless() {
		return contactless;
	}

	public void setUsim(BerNull usim) {
		this.usim = usim;
	}

	public BerNull getUsim() {
		return usim;
	}

	public void setIsim(BerNull isim) {
		this.isim = isim;
	}

	public BerNull getIsim() {
		return isim;
	}

	public void setCsim(BerNull csim) {
		this.csim = csim;
	}

	public BerNull getCsim() {
		return csim;
	}

	public void setMilenage(BerNull milenage) {
		this.milenage = milenage;
	}

	public BerNull getMilenage() {
		return milenage;
	}

	public void setTuak128(BerNull tuak128) {
		this.tuak128 = tuak128;
	}

	public BerNull getTuak128() {
		return tuak128;
	}

	public void setCave(BerNull cave) {
		this.cave = cave;
	}

	public BerNull getCave() {
		return cave;
	}

	public void setGbaUsim(BerNull gbaUsim) {
		this.gbaUsim = gbaUsim;
	}

	public BerNull getGbaUsim() {
		return gbaUsim;
	}

	public void setGbaIsim(BerNull gbaIsim) {
		this.gbaIsim = gbaIsim;
	}

	public BerNull getGbaIsim() {
		return gbaIsim;
	}

	public void setMbms(BerNull mbms) {
		this.mbms = mbms;
	}

	public BerNull getMbms() {
		return mbms;
	}

	public void setEap(BerNull eap) {
		this.eap = eap;
	}

	public BerNull getEap() {
		return eap;
	}

	public void setJavacard(BerNull javacard) {
		this.javacard = javacard;
	}

	public BerNull getJavacard() {
		return javacard;
	}

	public void setMultos(BerNull multos) {
		this.multos = multos;
	}

	public BerNull getMultos() {
		return multos;
	}

	public void setMultipleUsim(BerNull multipleUsim) {
		this.multipleUsim = multipleUsim;
	}

	public BerNull getMultipleUsim() {
		return multipleUsim;
	}

	public void setMultipleIsim(BerNull multipleIsim) {
		this.multipleIsim = multipleIsim;
	}

	public BerNull getMultipleIsim() {
		return multipleIsim;
	}

	public void setMultipleCsim(BerNull multipleCsim) {
		this.multipleCsim = multipleCsim;
	}

	public BerNull getMultipleCsim() {
		return multipleCsim;
	}

	public void setTuak256(BerNull tuak256) {
		this.tuak256 = tuak256;
	}

	public BerNull getTuak256() {
		return tuak256;
	}

	public int encode(BerByteArrayOutputStream os, boolean explicit) throws IOException {

		int codeLength;

		if (code != null) {
			codeLength = code.length;
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
		}
		else {
			codeLength = 0;
			if (tuak256 != null) {
				codeLength += tuak256.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 16
				os.write(0x90);
				codeLength += 1;
			}
			
			if (multipleCsim != null) {
				codeLength += multipleCsim.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 15
				os.write(0x8f);
				codeLength += 1;
			}
			
			if (multipleIsim != null) {
				codeLength += multipleIsim.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 14
				os.write(0x8e);
				codeLength += 1;
			}
			
			if (multipleUsim != null) {
				codeLength += multipleUsim.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 13
				os.write(0x8d);
				codeLength += 1;
			}
			
			if (multos != null) {
				codeLength += multos.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 12
				os.write(0x8c);
				codeLength += 1;
			}
			
			if (javacard != null) {
				codeLength += javacard.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 11
				os.write(0x8b);
				codeLength += 1;
			}
			
			if (eap != null) {
				codeLength += eap.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 10
				os.write(0x8a);
				codeLength += 1;
			}
			
			if (mbms != null) {
				codeLength += mbms.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 9
				os.write(0x89);
				codeLength += 1;
			}
			
			if (gbaIsim != null) {
				codeLength += gbaIsim.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 8
				os.write(0x88);
				codeLength += 1;
			}
			
			if (gbaUsim != null) {
				codeLength += gbaUsim.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 7
				os.write(0x87);
				codeLength += 1;
			}
			
			if (cave != null) {
				codeLength += cave.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 6
				os.write(0x86);
				codeLength += 1;
			}
			
			if (tuak128 != null) {
				codeLength += tuak128.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 5
				os.write(0x85);
				codeLength += 1;
			}
			
			if (milenage != null) {
				codeLength += milenage.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 4
				os.write(0x84);
				codeLength += 1;
			}
			
			if (csim != null) {
				codeLength += csim.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 3
				os.write(0x83);
				codeLength += 1;
			}
			
			if (isim != null) {
				codeLength += isim.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 2
				os.write(0x82);
				codeLength += 1;
			}
			
			if (usim != null) {
				codeLength += usim.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 1
				os.write(0x81);
				codeLength += 1;
			}
			
			if (contactless != null) {
				codeLength += contactless.encode(os, false);
				// write tag: CONTEXT_CLASS, PRIMITIVE, 0
				os.write(0x80);
				codeLength += 1;
			}
			
			codeLength += BerLength.encodeLength(os, codeLength);
		}

		if (explicit) {
			codeLength += id.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is, boolean explicit) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerIdentifier berIdentifier = new BerIdentifier();

		if (explicit) {
			codeLength += id.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berIdentifier.decode(is);
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 0)) {
			contactless = new BerNull();
			subCodeLength += contactless.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 1)) {
			usim = new BerNull();
			subCodeLength += usim.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 2)) {
			isim = new BerNull();
			subCodeLength += isim.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 3)) {
			csim = new BerNull();
			subCodeLength += csim.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 4)) {
			milenage = new BerNull();
			subCodeLength += milenage.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 5)) {
			tuak128 = new BerNull();
			subCodeLength += tuak128.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 6)) {
			cave = new BerNull();
			subCodeLength += cave.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 7)) {
			gbaUsim = new BerNull();
			subCodeLength += gbaUsim.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 8)) {
			gbaIsim = new BerNull();
			subCodeLength += gbaIsim.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 9)) {
			mbms = new BerNull();
			subCodeLength += mbms.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 10)) {
			eap = new BerNull();
			subCodeLength += eap.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 11)) {
			javacard = new BerNull();
			subCodeLength += javacard.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 12)) {
			multos = new BerNull();
			subCodeLength += multos.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 13)) {
			multipleUsim = new BerNull();
			subCodeLength += multipleUsim.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 14)) {
			multipleIsim = new BerNull();
			subCodeLength += multipleIsim.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 15)) {
			multipleCsim = new BerNull();
			subCodeLength += multipleCsim.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berIdentifier.decode(is);
		}
		
		if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.PRIMITIVE, 16)) {
			tuak256 = new BerNull();
			subCodeLength += tuak256.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder("SEQUENCE{");
		boolean firstSelectedElement = true;
		if (contactless != null) {
			sb.append("contactless: ").append(contactless);
			firstSelectedElement = false;
		}
		
		if (usim != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("usim: ").append(usim);
			firstSelectedElement = false;
		}
		
		if (isim != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("isim: ").append(isim);
			firstSelectedElement = false;
		}
		
		if (csim != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("csim: ").append(csim);
			firstSelectedElement = false;
		}
		
		if (milenage != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("milenage: ").append(milenage);
			firstSelectedElement = false;
		}
		
		if (tuak128 != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("tuak128: ").append(tuak128);
			firstSelectedElement = false;
		}
		
		if (cave != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("cave: ").append(cave);
			firstSelectedElement = false;
		}
		
		if (gbaUsim != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("gbaUsim: ").append(gbaUsim);
			firstSelectedElement = false;
		}
		
		if (gbaIsim != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("gbaIsim: ").append(gbaIsim);
			firstSelectedElement = false;
		}
		
		if (mbms != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("mbms: ").append(mbms);
			firstSelectedElement = false;
		}
		
		if (eap != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("eap: ").append(eap);
			firstSelectedElement = false;
		}
		
		if (javacard != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("javacard: ").append(javacard);
			firstSelectedElement = false;
		}
		
		if (multos != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("multos: ").append(multos);
			firstSelectedElement = false;
		}
		
		if (multipleUsim != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("multipleUsim: ").append(multipleUsim);
			firstSelectedElement = false;
		}
		
		if (multipleIsim != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("multipleIsim: ").append(multipleIsim);
			firstSelectedElement = false;
		}
		
		if (multipleCsim != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("multipleCsim: ").append(multipleCsim);
			firstSelectedElement = false;
		}
		
		if (tuak256 != null) {
			if (!firstSelectedElement) {
				sb.append(", ");
			}
			sb.append("tuak256: ").append(tuak256);
			firstSelectedElement = false;
		}
		
		sb.append("}");
		return sb.toString();
	}

}

